
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "1464248485715902497"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 26

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	[[init.presence]]
		type = "PLAYING"
		description = "AGLR SMP Yükleniyor..."
		state = "Oyun başlatılıyor..."
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = []
		smallImageText = "{{game.mods}} mod yüklü."
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	[[main_menu.presence]]
		type = "PLAYING"
		description = "{{player.name}} Ana menüde"
		state = "Ana menüde takılıyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{game.mods}} mod yüklü."
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	[[server_list.presence]]
		type = "PLAYING"
		description = "{{player.name}} sunuculara bakıyor"
		state = "Sunucu arıyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true

	[[realms_list.presence]]
		type = "PLAYING"
		description = "{{player.name}} Realm arıyor"
		state = "Realmlere Bakıyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	[[join_game.presence]]
		type = "PLAYING"
		description = "{{player.name}} bir oyuna katılıyor"
		state = "Oyuna katılıyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	[[single_player.presence]]
		type = "PLAYING"
		description = "Şu anda {{world.name}}"
		state = "Yalnız başına oynuyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	[[multi_player.presence]]
		type = "PLAYING"
		description = "{{server.name}} sunucusunda {{server.players.count}} kişiyle birlikte oynuyor"
		state = "Çevrimiçi oynuyor"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true

	[[realms.presence]]
		type = "PLAYING"
		description = "{{realm.name}} sunucusunda oynanıyor"
		state = "Bir Realm'de oynanıyor."
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = true

	[[paused.presence]]
		type = "PLAYING"
		description = "Duraklatma Menüsünde"
		state = "Oyun Durduruldu"
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#Fallback event for disabled events
[generic]

	[[generic.presence]]
		type = "PLAYING"
		description = "Minecraft Oynuyor"
		state = ""
		largeImageKey = ["mclogonew"]
		largeImageText = "aglrsmp"
		smallImageKey = ["mclogo"]
		smallImageText = "{{game.mods}} mods installed"
		streamingActivityUrl = "https://twitch.tv/twitch"
		buttons = []

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "overworld"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} Dünya'da"
			state = ""
			largeImageKey = ["overworld"]
			largeImageText = "Dünya Boyutunda"
			smallImageKey = ["mclogonew"]
			smallImageText = "aglrsmp"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} Nether'da"
			state = ""
			largeImageKey = ["nether"]
			largeImageText = "Nether Boyutunda"
			smallImageKey = ["mclogonew"]
			smallImageText = "aglrsmp"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} End'de"
			state = ""
			largeImageKey = ["end"]
			largeImageText = "End Boyutunda"
			smallImageKey = ["mclogonew"]
			smallImageText = "aglrsmp"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

