#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 11 21:01:09 TRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
